# pylint: skip-file

from typing import Dict

from cli.commandline import CLI
from clp.commandprocessor import CLP
from sqli.sqli import SQLI

NAME: str
VERSION: str
DATE: str

class SQLITESHELL:
    sqli: SQLI
    clp: CLP
    cli: CLI

    def __init__(self) -> None: ...
    def start(self) -> None: ...
    def exit(self, _: Dict[str, str]) -> None: ...
    def help(self, _: Dict[str, str]) -> None: ...
    def create(self, parms: Dict[str, str]) -> None: ...
    def open(self, parms: Dict[str, str]) -> None: ...
    def close(self, _: Dict[str, str]) -> None: ...
    def edit(self, parms: Dict[str, str]) -> None: ...

def main() -> None: ...
